### ISSUE TITLE
求助wifipineapple tetra关于SPI flash 16M的版本

### ISSUE THREAD

**Issue by zenxiaoshu** [suiyuinfo/wifipineapple-diy-rom#1]
你好，怎么编译一个SPI flash版本的tetra呢，我的ar9344搭配的16M flash，无法使用nand。我的uboot 有128K。谢谢

**Comment by suiyuinfo** [comment]
解包tetra固件，提取出文件来。在openwrt下建立files文件夹，将解包出来的内容拷贝到files文件夹下。
删除全部iptable，mod 和lib目录下modules文件夹。将pineapple\api\Setup.php文件中checkButtonStatus()改为        $buttonPressed = true;
        $bootStatus = true;
修改一下openwrt正常编译就好了。

**Comment by zenxiaoshu** [comment]
能指导下么？Q 1779860693

**Comment by suiyuinfo** [comment]
方法很详细了。而且我不玩QQ

**Comment by zenxiaoshu** [comment]
已经开始编译了 谢谢 就看能成功了不 在openwrt目录下建立files文件夹之后 这个编译会自动编进去么

**Comment by suiyuinfo** [comment]
如果你的是14以上自动编译进去，否则make FILES=files/ 

cd files
find ./ -name '*iptables*'|xargs rm -rf 
find ./ -name '*mod*'|xargs rm -rf 
rm -rf lib/modules

**Comment by zenxiaoshu** [comment]
非常感谢，我找到个文章：https://www.gl-inet.com/forums/topic/wifi-pineapple-nano-v1-0-6-firmware/
但是我在使用make FILES=files/ -j1 V=s 的时候，遇到了error：
make -C "/home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/linux-3.18.27" ARCH="mips" CROSS_COMPILE="mips-openwrt-linux-uclibc-" SUBDIRS="/home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/gpio-button-hotplug" modules
make[4]: Entering directory `/home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/linux-3.18.27'
  Building modules, stage 2.
  MODPOST 1 modules
make[4]: Leaving directory `/home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/linux-3.18.27'
touch /home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/gpio-button-hotplug/.built
mkdir -p /home/openwrt-cc/bin/ar71xx/packages /home/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/gpio-button-hotplug/ipkg-ar71xx/kmod-gpio-button-hotplug/CONTROL /home/openwrt-cc/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo
ERROR: module 'files/' is missing.
make[3]: *** [/home/openwrt-cc/bin/ar71xx/packages/base/kmod-gpio-button-hotplug_3.18.27-1_ar71xx.ipk] Error 1
make[3]: Leaving directory `/home/openwrt-cc/package/kernel/gpio-button-hotplug'
make[2]: *** [package/kernel/gpio-button-hotplug/compile] Error 2
make[2]: Leaving directory `/home/openwrt-cc'
make[1]: *** [/home/openwrt-cc/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/openwrt-cc'
make: *** [world] Error 2

**Comment by suiyuinfo** [comment]
删除掉FILES=files/再执行编译。貌似openwrt-cc默认支持的是AR160这款路由器吧。

**Comment by zenxiaoshu** [comment]
我更换了openwrt源码包，采用了15.05版本git下来，之后修改files完成，make menuconfig选择必要的模块等等，Target Profile选择TPLINK WDR4300包含这一项的，之后make -j1 V=s 编译成功，在bin/目录下有ar71xx文件夹，但是里面没有需要烧录的固件；只有如下文件：
root@MyServer:/home/openwrt/bin/ar71xx# ls -l
total 78456
-rw-r--r-- 1 root root      874 Nov 14 20:05 md5sums
-rwxr-xr-x 1 root root   160200 Nov 14 19:45 openwrt-ar71xx-generic-nbg460n_550n_550nh-u-boot.bin
-rw-r--r-- 1 root root 19529728 Nov 14 20:05 openwrt-ar71xx-generic-root.jffs2-128k
-rw-r--r-- 1 root root 19529728 Nov 14 20:05 openwrt-ar71xx-generic-root.jffs2-64k
-rw-r--r-- 1 root root 13762560 Nov 14 20:05 openwrt-ar71xx-generic-root.squashfs
-rw-r--r-- 1 root root 13434884 Nov 14 20:05 openwrt-ar71xx-generic-root.squashfs-64k
-rw-r--r-- 1 root root  1601328 Nov 14 20:38 openwrt-ar71xx-generic-uImage-gzip.bin
-rw-r--r-- 1 root root  1157014 Nov 14 20:38 openwrt-ar71xx-generic-uImage-lzma.bin
-rwxr-xr-x 1 root root  3509004 Nov 14 20:38 openwrt-ar71xx-generic-vmlinux.bin
-rwxr-xr-x 1 root root  3514068 Nov 14 20:38 openwrt-ar71xx-generic-vmlinux.elf
-rw-r--r-- 1 root root  1638400 Nov 14 20:38 openwrt-ar71xx-generic-vmlinux.gz
-rw-r--r-- 1 root root  1179648 Nov 14 20:38 openwrt-ar71xx-generic-vmlinux.lzma
-rwxr-xr-x 1 root root  1228977 Nov 14 20:38 openwrt-ar71xx-generic-vmlinux-lzma.elf
drwxr-xr-x 8 root root     4096 Nov 14 20:05 packages
-rw-r--r-- 1 root root     1439 Nov 14 20:05 sha256sums
drwxr-xr-x 2 root root     4096 Nov 14 20:34 uboot-ar71xx-nbg460n_550n_550nh

**Comment by zenxiaoshu** [comment]
已经编译成功，谢谢；需要修改makefile 规则为16MLZMA 不然文件限制大小，不会生成，不过我刷进去，机器要无限重启，信号这些都能收到，就是会重启，好悲剧；
你能分享一个WNDR4300的16M flash的tetra吗？我看下问题在哪儿

**Comment by suiyuinfo** [comment]
包太大了，你编译的超过了16M。

**Comment by suiyuinfo** [comment]
openwrt-ar71xx-nand-wndr4300-ubi-factory.img 可以直接刷入WNDR4300

**Comment by zenxiaoshu** [comment]
我使用的是SPI flash 16M ；nand flash已经坏掉。目前我正在自己修改固件文件，感觉这个挺有意思的。

**Comment by suiyuinfo** [comment]
去下载代码自己改一下吧。代码已经上传了。

**Comment by suiyuinfo** [comment]
需要修改 ./target/linux/ar71xx/image/Makefile 1058
这部分代码我还没看到，我也不知道该怎么修改。等我研究两天。

**Comment by suiyuinfo** [comment]
你可以尝试一下使用TP-LINK WDR4300的固件。

**Comment by zenxiaoshu** [comment]
已经成功 非常感谢 我基本清楚了openwrt目录文件的用途，我用了一个AR9344 DIY板子，自己编了内核补丁相关文件，根据硬件配置，在make menuconfig新加入了一个机型，补丁path文件打好之后，make完美，非常感谢。
下一步将深入学习 ing。有空多交流下

**Comment by zenxiaoshu** [comment]
突然觉得 这个wifipineapple 基本可以编译在任何的支持openwrt机器上面，只要清楚补丁等。
我参考了：
http://blog.chinaunix.net/uid-29616823-id-4477611.html（打补丁的方法）
http://blog.csdn.net/x901205/article/details/38829261（增加新机型）
代码结构也不复杂，我打算移植到最新的openwrt 15.05.1版本上去，然后自己做一些自己喜欢的功能。

**Comment by zenxiaoshu** [comment]
突然觉得 这个wifipineapple 基本可以编译在任何的支持openwrt机器上面，只要清楚补丁等。
我参考了：
http://blog.chinaunix.net/uid-29616823-id-4477611.html（打补丁的方法）
http://blog.csdn.net/x901205/article/details/38829261（增加新机型）
代码结构也不复杂，我打算移植到最新的openwrt 15.05.1版本上去，然后自己写一些自己喜欢的功能

**Comment by zenxiaoshu** [comment]
突然觉得 这个wifipineapple 基本可以编译在任何的支持openwrt机器上面，只要清楚补丁等。
我参考了：
http://blog.chinaunix.net/uid-29616823-id-4477611.html（打补丁的方法）
http://blog.csdn.net/x901205/article/details/38829261（增加新机型）
代码结构也不复杂，我打算移植到最新的openwrt 15.05.1版本上去，然后自己写一些自己喜欢的功能

**Comment by zenxiaoshu** [comment]
突然觉得 这个wifipineapple 基本可以编译在任何的支持openwrt机器上面，只要清楚补丁等。
我参考了：
http://blog.chinaunix.net/uid-29616823-id-4477611.html（打补丁的方法）
http://blog.csdn.net/x901205/article/details/38829261（增加新机型）
代码结构也不复杂，我打算移植到最新的openwrt 15.05.1版本上去，然后自己写一些自己喜欢的功能

**Comment by zenxiaoshu** [comment]
突然觉得 这个wifipineapple 基本可以编译在任何的支持openwrt机器上面，只要清楚补丁等。
我参考了：
http://blog.chinaunix.net/uid-29616823-id-4477611.html（打补丁的方法）
http://blog.csdn.net/x901205/article/details/38829261（增加新机型）
代码结构也不复杂，我打算移植到最新的openwrt 15.05.1版本上去，然后自己写一些自己喜欢的功能

**Comment by zenxiaoshu** [comment]
Makefile增加自己的机型代码
$(eval $(call SingleProfile,TPLINK-LZMA,$(fs_64kraw),MYSELFBORAD,myselfboard,myselfboard,ttyS0,115200,0x60000001,1,16Mlzma))

**Comment by suiyuinfo** [comment]
理论上全部支持，但是部分软件不开源，无法全部支持。其他的功能基本上全部移植没问题。

**Comment by zenxiaoshu** [comment]
你的运行在wndr4300上面，有线的WAN口和4个LAN口功能有变更么？
